### PR TITLE
Support `label_fieldName` auto-complete templates, e.g. `*_dateOfBirth` (RPB-169)

### PR DESCRIPTION
**Pull request by fsteeg**
E.g. [preferredName,*_dateOfBirth in_placeOfBirth,†_dateOfDeath in_placeOfDeath](https://test.lobid.org/gnd/search?q=Twain&format=json%3ApreferredName%2C*_dateOfBirth+in_placeOfBirth%2C%E2%80%A0_dateOfDeath+in_placeOfDeath)

New sample at https://test.lobid.org/gnd/api#auto-complete

See https://jira.hbz-nrw.de/browse/RPB-169

### CODE REVIEW

**Comment by acka47** [comment]
I also notcied that the results of these queries are not pretty-printed when queried with curl, e.g.:

```
$ curl"https://test.lobid.org/gnd/search?q=Twain&format=json%3ApreferredName%2C*_dateOfBirth+in_placeOfBirth%2C%E2%80%A0_dateOfDeath+in_placeOfDeath"
[{"label":"Twain (Musikgruppe)","id":"https://d-nb.info/gnd/1229526226","category":"Musikalische Körperschaft"},{"image":"https://commons.wikimedia.org/wiki/Special:FilePath/Shania%20Twain%20March%202020.png?width=100","label":"Twain, Shania | * 1965 in Windsor (Ontario)","id":"https://d-nb.info/gnd/121570924","category":"Individualisierte Person"},{"label":"These Twain","id":"https://d-nb.info/gnd/1215051689","category":"Werk"},{"image":"https://commons.wikimedia.org/wiki/Special:FilePath/MarkTwain.LOC.jpg?width=100","label":"Twain, Mark | * 1835 in Florida, Mo. | † 1910 in Redding, Conn.","id":"https://d-nb.info/gnd/118624822","category":"Individualisierte Person"},{"label":"Bezirkszentralbibliothek Mark Twain. Schreibwerkstatt","id":"https://d-nb.info/gnd/1045623490","category":"Körperschaft"},{"label":"Mark-Twain-Schule","id":"https://d-nb.info/gnd/1150522305","category":"Körperschaft"},{"label":"Bezirkszentralbibliothek Mark Twain","id":"https://d-nb.info/gnd/1045623113","category":"Körperschaft"},{"label":"Twain, K. V. | * 1981 in Galatz","id":"https://d-nb.info/gnd/1179733045","category":"Individualisierte Person"},{"label":"International Mark Twain Society","id":"https://d-nb.info/gnd/75281-2","category":"Körperschaft"},{"label":"Autobiography of Mark Twain","id":"https://d-nb.info/gnd/1081942517","category":"Werk"}]
```

As we pretty-print – so far as I knwo – all other responses, this should also be pretty-printed for sake of consistency.

**Comment by acka47** [comment]
> While several occupation are already automatically concatenated by commas, this is not the case for `placeOfActivity`.

Looking at the implementation in https://github.com/hbz/strapi-rpb/pull/31/files#diff-464e263cd47a4e96e7232665ebc65ba8aeb2f4377fadcef146a855feca83028cR5-R6 it seems to work. So I hav edone something wrong or do not understand fully how this works:

https://test.lobid.org/gnd/search?q=Friedrich+Schiller+arzt&format=json%3ApreferredName,*_dateOfBirth+_placeOfBirth,%E2%80%A0_dateOfDeath+_placeOfDeath,placeOfActivity,professionOrOccupation

**Comment by fsteeg** [comment]
> While several occupation are already automatically concatenated by commas, this is not the case for `placeOfActivity` [...] it seems to work. So I have done something wrong or do not understand fully how this works

No, good catch, it only worked for the old, plain-field syntax, not for the new templates. Fixed on test, see [your query](https://test.lobid.org/gnd/search?q=Friedrich+Schiller+arzt&format=json%3ApreferredName%2CprofessionOrOccupation%2C*_dateOfBirth+in_placeOfBirth%2C%E2%80%A0_dateOfDeath+in_placeOfDeath%2Cwirkte+in_placeOfActivity) and an example [in RPPD](http://test.rppd.lobid.org/search?q=placeOfActivity:*&format=json%3ApreferredName%2CprofessionOrOccupation%2C*_dateOfBirth+in_placeOfBirth%2C%E2%80%A0_dateOfDeath+in_placeOfDeath%2Cwirkte+in_placeOfActivity) (I changed the delimiter from `,` to `;` since `,` is often used in field values).

> As we pretty-print – so far as I know – all other responses, this should also be pretty-printed for sake of consistency.

Fixed on test, see "View Page Source" on the examples above or
`curl "https://test.lobid.org/gnd/search?q=Twain&format=json:suggest"`

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
