### PR TITLE
Switch to new GND full dump format

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve https://github.com/hbz/lobid-gnd/issues/146

### CODE REVIEW

**Comment by fsteeg** [comment]
Merged in https://github.com/hbz/lobid-gnd/commit/0f6c4cd8770848076cd8ba8960a21f4ee91c9f22, closing.

> wondering why there are no json-ld test-files but turtle?

The turtle files are used to test the conversion from RDF to JSON-LD.

**Comment by dr0i** [comment]
@fsteeg can you elaborate a bit? Turtle is also RDF, no? 
And indeed, where is the JSON-LD when testing the conversion to it?
I don't understand.

**Comment by fsteeg** [comment]
> @fsteeg can you elaborate a bit? Turtle is also RDF, no?

Right. Not sure what you mean. The Turtle files are the RDF used for testing the transformation.

> And indeed, where is the JSON-LD when testing the conversion to it?

For the conversion tests, the RDF is transformed, parsed, and tested in memory.

For indexing tests, the JSON-LD is written to `*.jsonl` files (in `test/data/index`, not versioned).

**Comment by dr0i** [comment]
Yes, and I would expect to test against expected JSON-LD, as it may vary from the pure turtle/rdfxml/ntriples/whatever because of i.a. the JSON-LD-context.

**Comment by fsteeg** [comment]
> Yes, and I would expect to test against expected JSON-LD, as it may vary from the pure turtle/rdfxml/ntriples/whatever because of i.a. the JSON-LD-context.

Sure, the tests do test the actual JSON-LD, but not by comparing it to expected JSON-LD files, but by checking fields in the JSON-LD etc. See e.g. https://github.com/hbz/lobid-gnd/blob/master/test/apps/ConvertTest.java#L70

**Comment by dr0i** [comment]
well - ok

**Comment by dr0i** [comment]
Uh - I have the feeling that it would be the best, in general,  to compare the whole structure, as JSON-LD is rather  complex, but it may well be your tests are fine! Yeah let's talk about it then on thursday.

**Pull request closed without merging**
