### PR TITLE
Use en dash for date ranges

### LINKED ISSUE #305: Use en dash for date ranges
When putting together `dateOfBirth` and `dateOfDeath` for the subtitle in the HTML details view there should be a typographically correct `en dash` between those values instead of a normal dash. 

In the search result overview an `en dash` is used already, but it should come without surrounding spaces.

### PR DESCRIPTION
**Pull request by rettinghaus**
Fixes #305.

### CODE REVIEW

**Comment by fsteeg** [comment]
Thanks for the PR @rettinghaus!

I think you got the wrong places for replacing the hyphens. The ones you replaced are only used internally / in the `format` query parameter as a marker  (`dateOfBirth-dateOfDeath`). The actual output string (e.g. `1835-1910`) should be the one generated here:

https://github.com/hbz/lobid-gnd/blob/92d96db2057e5e09c936350d410d2572c800ef86/app/models/AuthorityResource.java#L458

**Comment by rettinghaus** [comment]
@fsteeg Thanks for pointing me to this. Wouldn't have identified `v1` and `v2` as dates. 🤣

**Comment by fsteeg** [comment]
I don't think the other hyphens (from your original commit) should actually be replaced, that would make usage cumbersome (entering the en dash when configuring a call) and break existing usage of that API (even if it's undocumented).

**Review by fsteeg — APPROVED** [review]
Just noticed you had pushed changes last week, thanks (even when watching "All Activity" in hbz/lobid-gnd, I don't get notifications for pushed commits here, I've now also set up watching "All Activity" in your fork). Pushed one minor tweak in 04ce842.

Deployed to test, looks good to me, will deploy to production:

https://test.lobid.org/gnd/search?q=heinrich+böll
https://test.lobid.org/gnd/118512676

Thanks again for contributing!

**Pull request merged**
