### PR TITLE
Fix `@context` for `usingInstructions`& `professionOrOccupation`

### LINKED ISSUE #333: Missing MARC field 680 in RDF
Reported via email by @stefandesu for Cocoda. I opened a corresponding Jira issue at DNB: https://jira.dnb.de/browse/GND-226

Am 07.12.22 um 11:56 schrieb Peters, Stefan:

> ... Dabei ist mir aufgefallen, dass die Daten, die auf der Seite der DNB unter "Erläuterungen" stehen (also insb. Verwendungshinweise) nicht in lobid eingespielt sind.
> 
> Beispiel: 4053474-1 Schule
> lobid: https://lobid.org/gnd/4053474-1
> DNB: https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4053474-1
> 
> Diese Daten wären jedoch für die Anzeige in Cocoda recht wichtig. Ich vermute, das Problem liegt daran, dass diese Daten nicht im RDF-Datensatz der DNB vorhanden sind, kann das sein? In MARC-XML sind sie vorhanden in Feld 680. Meinst du, es wäre möglich, diese Daten auch über lobid zu bekommen?

### PR DESCRIPTION
**Pull request by acka47**
Should finally resolve (partially) #333 . Might resolve (partially) https://github.com/hbz/lobid/issues/419 .

### CODE REVIEW

**Comment by fsteeg** [comment]
Deployed, will be used for tonight's updates. What about the `professionOrOccupation` errors?

**Comment by acka47** [comment]
> What about the `professionOrOccupation` errors?

These might be fixed with https://github.com/hbz/lobid-gnd/pull/360/commits/1f10a4e4ddac0cc0ea812f98e5a2cf3caf3e6da8 .
The respective issue is https://github.com/hbz/lobid/issues/419 (we should have moved that to the lobid-gnd repo, I always have trouble finding it).

**Comment by fsteeg** [comment]
Also deployed https://github.com/hbz/lobid-gnd/commit/1f10a4e4ddac0cc0ea812f98e5a2cf3caf3e6da8 for tonight's updates.

**Comment by fsteeg** [comment]
Pushed https://github.com/hbz/lobid-gnd/pull/360/commits/a06af85075fce419a47285c915c5e717b4721564, looks good for the tests. Deployed to the servers for nightly updates. We will still get the alert since the current test index will remain broken, but we should be able to check the updates. I've also triggered creating a new baseline index for testing, so we should be able to get an up-to-date index next week.

**Comment by acka47** [comment]
`professionOrOccupation` looks better now. In those records changed on Friday, the order looks good as well: https://test.lobid.org/gnd/search?q=describedBy.dateModified%3A2023-11-03+AND+_exists_%3AprofessionOrOccupation&format=json

However, it does not look good for others but I guess, the changes only apply to the latest modifications, don't they?

Re. `usageInstructions` we had already seen that it works, hadn't we (but I can not find an example on test now to verify)?

**Comment by fsteeg** [comment]
> However, it does not look good for others but I guess, the changes only apply to the latest modifications, don't they?

Yes, we will have to re-index updates into a clean index. I will test with the new test index I created, and if that works I will re-index the missing updates into the current production index.

**Comment by fsteeg** [comment]
Deployed updates to (new) test setup, no uncompacted fields, looks good:

- [describedBy.dateModified:2023-11-01+AND+professionOrOccupation:*&format=json](http://test.lobid.org/gnd/search?q=describedBy.dateModified:2023-11-01+AND+professionOrOccupation:*&format=json) (order looks good too, e.g. [1308235011](http://test.lobid.org/gnd/1308235011), [1308234414](http://test.lobid.org/gnd/1308234414))
- [http://test.lobid.org/gnd/search?q=usingInstructions:*](http://test.lobid.org/gnd/search?q=usingInstructions:*)

 (Note: test does not contain all data, only June basedump + updates since 2023-10-10; it's also in a weird state otherwise: the baseline data has the old `professionOrOccupation` structure, leading to empty arrays for those entries. Also the current EntityFacts dump caused an error, resulting in missing depictions etc. on test; all of this should not be relevant for the production setup, which had working updates before 2023-10-10, and is still using the full EntityFacts index.)

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, corresponding to the test links above:

- [describedBy.dateModified:2023-11-01+AND+professionOrOccupation:*&format=json](http://lobid.org/gnd/search?q=describedBy.dateModified:2023-11-01+AND+professionOrOccupation:*&format=json) (order looks good too, e.g. [1308235011](http://lobid.org/gnd/1308235011), [1308234414](http://lobid.org/gnd/1308234414))
- [http://lobid.org/gnd/search?q=usingInstructions:*](http://lobid.org/gnd/search?q=usingInstructions:*)

Will merge, but will remove the closing references before (https://github.com/hbz/lobid-gnd/issues/333, https://github.com/hbz/lobid/issues/419) since these will only be resolved after a new baseline.

**Pull request merged**
